### ISSUE TITLE
Difference between your and aguslr version? & suggestion

### ISSUE THREAD

**Issue by dko1905** [hackerncoder/multibootusb#37]
## Question
Can you please describe the difference between your and aguslrs version?
Are there any improvements?

## Suggestion
Can you add the answer from the previous question to the README?
And maybe clarify that it's your fork.

**Comment by hackerncoder** [comment]
Mine has many of the pull request from aguslrs approved, meaning many more distros will work.
Oh, and also, I am not dead. (Not that I am curating this every day, but still)
And i will do that.

**Comment by hackerncoder** [comment]
Done. Thanks for bringing it to my attention.
