### ISSUE TITLE
makeUSB.sh does not work on Fedora

### ISSUE THREAD

**Issue by dko1905** [hackerncoder/multibootusb#39]
The script does not work on Fedora 32.
Here is the output:
<pre><font color="#4E9A06"><b>➜  </b></font><font color="#06989A"><b>multibootusb</b></font> <font color="#3465A4"><b>git:(</b></font><font color="#CC0000"><b>master</b></font><font color="#3465A4"><b>)</b></font> ./makeUSB.sh /dev/sda ext4 28G -e
This script must be run as root. Using sudo...
[sudo] password for daniel: 
Are you sure you want to use /dev/sda? [y/N] Y
THIS WILL DELETE ALL DATA ON THE DEVICE. Are you sure? [y/N] Y

# Remove partitions
sgdisk --zap-all &quot;$usb_dev&quot;
GPT data structures destroyed! You may now partition the disk using fdisk or
other utilities.

# Create GUID Partition Table
sgdisk --mbrtogpt &quot;$usb_dev&quot; || cleanUp 10
Creating new GPT entries in memory.
The operation has completed successfully.

# Create BIOS boot partition (1M)
sgdisk --new 1::+1M --typecode 1:ef02 \
    --change-name 1:&quot;BIOS boot partition&quot; &quot;$usb_dev&quot; || cleanUp 10
Setting name!
partNum is 0
The operation has completed successfully.

# Create EFI System partition (50M)
[ &quot;$eficonfig&quot; -eq 1 ] &amp;&amp; \
    { sgdisk --new 2::+50M --typecode 2:ef00 \
    --change-name 2:&quot;EFI System&quot; &quot;$usb_dev&quot; || cleanUp 10; }
Setting name!
partNum is 1
The operation has completed successfully.

# Set data partition size
[ -z &quot;$data_size&quot; ] || \
    data_size=&quot;+$data_size&quot;

# Set data partition information
case &quot;$data_fmt&quot; in
	ext2|ext3|ext4)
		type_code=&quot;8300&quot;
		part_name=&quot;Linux filesystem&quot;
		;;
	msdos|fat|vfat|ntfs)
		type_code=&quot;0700&quot;
		part_name=&quot;Microsoft basic data&quot;
		;;
	*)
		printf &apos;%s: %s is an invalid filesystem type.\n&apos; &quot;$scriptname&quot; &quot;$data_fmt&quot; &gt;&amp;2
		showUsage
		cleanUp 1
		;;
esac

# Create data partition
sgdisk --new ${data_part}::&quot;${data_size}&quot;: --typecode ${data_part}:&quot;$type_code&quot; \
    --change-name ${data_part}:&quot;$part_name&quot; &quot;$usb_dev&quot; || cleanUp 10
Setting name!
partNum is 2
The operation has completed successfully.

# Unmount device
unmountUSB &quot;$usb_dev&quot;

# Interactive configuration?
if [ &quot;$interactive&quot; -eq 1 ]; then
	# Create hybrid MBR manually
	# https://bit.ly/2z7HBrP
	gdisk &quot;$usb_dev&quot;
elif [ &quot;$hybrid&quot; -eq 1 ]; then
	# Create hybrid MBR
	if [ &quot;$eficonfig&quot; -eq 1 ]; then
		sgdisk --hybrid 1:2:3 &quot;$usb_dev&quot; || cleanUp 10
	else
		sgdisk --hybrid 1:2 &quot;$usb_dev&quot; || cleanUp 10
	fi
fi

# Set bootable flag for data partion
sgdisk --attributes ${data_part}:set:2 &quot;$usb_dev&quot; || cleanUp 10
The operation has completed successfully.

# Unmount device
unmountUSB &quot;$usb_dev&quot;

# Wipe BIOS boot partition
wipefs -af &quot;${usb_dev}1&quot; || true

# Format EFI System partition
if [ &quot;$eficonfig&quot; -eq 1 ]; then
	wipefs -af &quot;${usb_dev}2&quot; || true
	mkfs.vfat -v -F 32 &quot;${usb_dev}2&quot; || cleanUp 10
fi
/dev/sda2: 8 bytes were erased at offset 0x00000052 (vfat): 46 41 54 33 32 20 20 20
/dev/sda2: 1 byte was erased at offset 0x00000000 (vfat): eb
/dev/sda2: 2 bytes were erased at offset 0x000001fe (vfat): 55 aa
mkfs.fat 4.1 (2017-01-24)
/dev/sda2 has 64 heads and 32 sectors per track,
hidden sectors 0x1000;
logical sector size is 512,
using 0xf8 media descriptor, with 102400 sectors;
drive number 0x80;
filesystem has 2 32-bit FATs and 1 sector per cluster.
FAT size is 788 sectors, and provides 100792 clusters.
There are 32 reserved sectors.
Volume ID is 6fab29c7, no volume label.

# Wipe data partition
wipefs -af &quot;${usb_dev}${data_part}&quot; || true

# Format data partition
if [ &quot;$data_fmt&quot; = &quot;ntfs&quot; ]; then
	# Use mkntfs quick format
	mkfs -t &quot;$data_fmt&quot; -f &quot;${usb_dev}${data_part}&quot; || cleanUp 10
else
	mkfs -t &quot;$data_fmt&quot; &quot;${usb_dev}${data_part}&quot;    || cleanUp 10
fi
mke2fs 1.45.5 (07-Jan-2020)
Creating filesystem with 7340032 4k blocks and 1835008 inodes
Filesystem UUID: 9ac97385-ff3c-4525-9ddc-e6d4f887cf07
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
	4096000

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done   

# Unmount device
unmountUSB &quot;$usb_dev&quot;

# Create temporary directories
efi_mnt=$(mktemp -p &quot;$tmp_dir&quot; -d efi.XXXX)   || cleanUp 10
data_mnt=$(mktemp -p &quot;$tmp_dir&quot; -d data.XXXX) || cleanUp 10
repo_dir=$(mktemp -p &quot;$tmp_dir&quot; -d repo.XXXX) || cleanUp 10

# Mount EFI System partition
[ &quot;$eficonfig&quot; -eq 1 ] &amp;&amp; \
    { mount &quot;${usb_dev}2&quot; &quot;$efi_mnt&quot; || cleanUp 10; }

# Mount data partition
mount &quot;${usb_dev}${data_part}&quot; &quot;$data_mnt&quot; || cleanUp 10

# Install GRUB for EFI
[ &quot;$eficonfig&quot; -eq 1 ] &amp;&amp; \
    { $grub_cmd --target=x86_64-efi --efi-directory=&quot;$efi_mnt&quot; \
    --boot-directory=&quot;${data_mnt}/${data_subdir}&quot; --removable --recheck \
    || cleanUp 10; }
/usr/sbin/grub2-install: error: /usr/lib/grub/x86_64-efi/modinfo.sh doesn&apos;t exist. Please specify --target or --directory.</pre>

I thinks it's something with the grub configuration on Fedora.

**Comment by drnest** [comment]
Try add package grub2-efi-x64-modules.

**Comment by dko1905** [comment]
I have switched away from Fedora, so I'll think I'll close this issue.
