### ISSUE TITLE
archlinux-2020.09.01-x86_64.iso fails to boot

### ISSUE THREAD

**Issue by cmonty14** [hackerncoder/multibootusb#43]
Hi,

I have setup USB stick according the instructions.
Now I want to boot _archlinux-2020.09.01-x86_64.iso_ but this fails with error:
```
error: file '/arch/boot/x86_64/vmlinuz' not found
error: you need to load the kernel first.

Press any key to continue...
```

To verify if the setup is wrong I try to boot another iso _tails-amd64-4.10.iso_ and this works w/o problems.

Please advise how to fix this issue.

THX

**Comment by hackerncoder** [comment]
I just downloaded arch 2020.10.01 and it has `vmlinuz-linux` instead of `vmlinuz`. The arch cfg might need to be updated to use that.
