### ISSUE TITLE
there is another project mbusb/multibootusb which is inspired by aguslr/multibootusb

### ISSUE THREAD

**Issue by braindevices** [hackerncoder/multibootusb#51]
there is another project mbusb/multibootusb which is inspired by aguslr/multibootusb. Maybe you can consider to take over that or even better merge their work.

**Comment by nothingnesses** [comment]
That's a completely different project unrelated to aguslr/multibootusb and only coincidentally has the same name.

**Comment by hackerncoder** [comment]
as @nothingnesses says: It's a completely different project, so I cannot merge what they have done. I also do not want to add another ESR to my profile.
